# Generated by Django 5.1.7 on 2025-03-30 11:27

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='group_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='member_emails',
            field=models.TextField(default='string', help_text='Comma-separated list of member email addresses', validators=[pages.models.validate_email_list]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Group name', max_length=100, unique=True),
        ),
    ]
