# Generated by Django 5.1.7 on 2025-04-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_quarterfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quarter',
            options={'ordering': ['-number']},
        ),
        migrations.AlterField(
            model_name='quarter',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
