<<<<<<< HEAD
# Generated by Django 5.2 on 2025-04-17 15:29
=======
# Generated by Django 5.2 on 2025-04-18 21:06
>>>>>>> master

import django.db.models.deletion
import pages.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-number'],
                'unique_together': {('user', 'number')},
            },
        ),
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=pages.models.user_quarter_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('section_name', models.CharField(blank=True, editable=False, max_length=255)),
<<<<<<< HEAD
            ],
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
=======
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_files', to=settings.AUTH_USER_MODEL)),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='pages.quarter')),
>>>>>>> master
            ],
            options={
                'unique_together': {('user', 'uuid')},
            },
        ),
        migrations.CreateModel(
            name='CSVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name_pretty', models.CharField(max_length=255)),
                ('sheet_name_slug', models.CharField(max_length=255)),
                ('quarter_uuid', models.UUIDField(editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
                ('data', models.JSONField(default=list)),
                ('quarter_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csvs', to='pages.excelfile')),
            ],
        ),
        migrations.AddField(
            model_name='excelfile',
            name='quarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='pages.quarter'),
=======
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_data', to=settings.AUTH_USER_MODEL)),
                ('quarter_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csvs', to='pages.excelfile')),
            ],
            options={
                'unique_together': {('user', 'uuid')},
            },
>>>>>>> master
        ),
    ]
