# Generated by Django 5.2 on 2025-04-17 15:29

import django.db.models.deletion
import pages.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=pages.models.user_quarter_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('section_name', models.CharField(blank=True, editable=False, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='CSVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name_pretty', models.CharField(max_length=255)),
                ('sheet_name_slug', models.CharField(max_length=255)),
                ('quarter_uuid', models.UUIDField(editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=list)),
                ('quarter_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csvs', to='pages.excelfile')),
            ],
        ),
        migrations.AddField(
            model_name='excelfile',
            name='quarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='pages.quarter'),
        ),
    ]
