# Generated by Django 5.1.7 on 2025-04-01 18:27

import django.db.models.deletion
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=pages.models.user_quarter_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='pages.quarter')),
            ],
        ),
    ]
