# Generated by Django 5.2 on 2025-04-18 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarter',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='csvdata',
            unique_together={('user', 'uuid')},
        ),
        migrations.AlterUniqueTogether(
            name='excelfile',
            unique_together={('user', 'uuid')},
        ),
        migrations.AlterUniqueTogether(
            name='quarter',
            unique_together={('user', 'number')},
        ),
    ]
