# Generated by Django 5.1.7 on 2025-04-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excellfile',
            name='file_name',
            field=models.TextField(default='hello', editable=False),
        ),
    ]
