# Generated by Django 5.2 on 2025-04-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdata',
            name='column_order',
            field=models.JSONField(default=list),
        ),
    ]
