# Generated by Django 5.1.7 on 2025-04-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excellfile',
            name='file_name',
        ),
        migrations.AddField(
            model_name='excellfile',
            name='section_name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
