# Generated by Django 5.1.7 on 2025-04-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_excellfile_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excellfile',
            name='file_name',
            field=models.TextField(editable=False),
        ),
    ]
