name: Build LaTeX Report

on:
  push:
    branches:
      - "*"
    paths:
      - '**.tex'

jobs:
  build-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (with cache)
        uses: docker/build-push-action@v5
        with:
          context: ./docs/final_report
          file: ./docs/final_report/Dockerfile  # ajusta o caminho se necessário
          tags: final-report-image:latest
          load: true  # Faz o build e carrega a imagem localmente
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run LaTeX build script
        run: |
          docker run --rm -v ${{ github.workspace }}/docs/final_report:/data final-report-image ./docker.sh runonly

      - name: Upload compiled PDF
        uses: actions/upload-artifact@v4
        with:
          name: final-report
          path: docs/final_report/build/final_report.pdf
